# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/build-katte-extreme/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test-tokenizer-0-bert-bge]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-bert-bge.gguf")
set_tests_properties([=[test-tokenizer-0-bert-bge]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;122;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-command-r]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-command-r.gguf")
set_tests_properties([=[test-tokenizer-0-command-r]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;123;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-coder]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-coder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;124;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-llm]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-llm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;125;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-falcon]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-falcon.gguf")
set_tests_properties([=[test-tokenizer-0-falcon]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;126;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gemma-4]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-gemma-4.gguf")
set_tests_properties([=[test-tokenizer-0-gemma-4]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;127;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gpt-2]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-gpt-2.gguf")
set_tests_properties([=[test-tokenizer-0-gpt-2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;128;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-bpe]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties([=[test-tokenizer-0-llama-bpe]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;129;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-spm]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-0-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;130;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-mpt]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-mpt.gguf")
set_tests_properties([=[test-tokenizer-0-mpt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;131;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-phi-3]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-phi-3.gguf")
set_tests_properties([=[test-tokenizer-0-phi-3]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;132;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen2]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-qwen2.gguf")
set_tests_properties([=[test-tokenizer-0-qwen2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;133;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen35]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-qwen35.gguf")
set_tests_properties([=[test-tokenizer-0-qwen35]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;134;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-refact]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-refact.gguf")
set_tests_properties([=[test-tokenizer-0-refact]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;135;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-starcoder]=] "/workspace/build-katte-extreme/bin/test-tokenizer-0" "/workspace/models/ggml-vocab-starcoder.gguf")
set_tests_properties([=[test-tokenizer-0-starcoder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;136;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizers-ggml-vocabs]=] "/workspace/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "/workspace/models/ggml-vocabs")
set_tests_properties([=[test-tokenizers-ggml-vocabs]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/workspace/build-katte-extreme/bin" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;68;add_test;/workspace/tests/CMakeLists.txt;139;llama_test_cmd;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-unicode]=] "/workspace/build-katte-extreme/bin/test-unicode")
set_tests_properties([=[test-unicode]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;156;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-sampling]=] "/workspace/build-katte-extreme/bin/test-sampling")
set_tests_properties([=[test-sampling]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;157;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-reasoning-budget]=] "/workspace/build-katte-extreme/bin/test-reasoning-budget")
set_tests_properties([=[test-reasoning-budget]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;158;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-parser]=] "/workspace/build-katte-extreme/bin/test-grammar-parser")
set_tests_properties([=[test-grammar-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;159;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-integration]=] "/workspace/build-katte-extreme/bin/test-grammar-integration")
set_tests_properties([=[test-grammar-integration]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;160;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-llama-grammar]=] "/workspace/build-katte-extreme/bin/test-llama-grammar")
set_tests_properties([=[test-llama-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;161;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-batch-alloc]=] "/workspace/build-katte-extreme/bin/test-batch-alloc")
set_tests_properties([=[test-batch-alloc]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;162;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-chat]=] "/workspace/build-katte-extreme/bin/test-chat")
set_tests_properties([=[test-chat]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/workspace" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;163;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-json-schema-to-grammar]=] "/workspace/build-katte-extreme/bin/test-json-schema-to-grammar")
set_tests_properties([=[test-json-schema-to-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;166;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-1-llama-spm]=] "/workspace/build-katte-extreme/bin/test-tokenizer-1-spm" "/workspace/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-1-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;190;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-generate-models]=] "/workspace/build-katte-extreme/bin/test-llama-archs" "-o" "/workspace/build-katte-extreme/tests/test-models/")
set_tests_properties([=[test-generate-models]=] PROPERTIES  FIXTURES_SETUP "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;200;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-recurrent-state-rollback]=] "/workspace/build-katte-extreme/bin/test-recurrent-state-rollback" "-m" "/workspace/build-katte-extreme/tests/test-models//qwen35-dense.gguf")
set_tests_properties([=[test-recurrent-state-rollback]=] PROPERTIES  FIXTURES_REQUIRED "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;210;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-recurrent-state-rollback-nemotron-h]=] "/workspace/build-katte-extreme/bin/test-recurrent-state-rollback" "-m" "/workspace/build-katte-extreme/tests/test-models//nemotron_h-dense.gguf")
set_tests_properties([=[test-recurrent-state-rollback-nemotron-h]=] PROPERTIES  FIXTURES_REQUIRED "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;219;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-recurrent-state-rollback-dsv4]=] "/workspace/build-katte-extreme/bin/test-recurrent-state-rollback" "-m" "/workspace/build-katte-extreme/tests/test-models//deepseek4-moe.gguf")
set_tests_properties([=[test-recurrent-state-rollback-dsv4]=] PROPERTIES  FIXTURES_REQUIRED "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;228;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-recurrent-state-rollback-kimi-k3]=] "/workspace/build-katte-extreme/bin/test-recurrent-state-rollback" "-m" "/workspace/build-katte-extreme/tests/test-models//kimi-k3-moe.gguf")
set_tests_properties([=[test-recurrent-state-rollback-kimi-k3]=] PROPERTIES  FIXTURES_REQUIRED "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;237;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-save-load-state]=] "/workspace/build-katte-extreme/bin/test-save-load-state" "--models" "/workspace/build-katte-extreme/tests/test-models/")
set_tests_properties([=[test-save-load-state]=] PROPERTIES  FIXTURES_REQUIRED "generate-models" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;248;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-chat-peg-parser]=] "/workspace/build-katte-extreme/bin/test-chat-peg-parser")
set_tests_properties([=[test-chat-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;258;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-jinja]=] "/workspace/build-katte-extreme/bin/test-jinja")
set_tests_properties([=[test-jinja]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;259;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-jinja-py]=] "/workspace/build-katte-extreme/bin/test-jinja" "-py")
set_tests_properties([=[test-jinja-py]=] PROPERTIES  LABELS "python" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;260;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-json-schema]=] "/workspace/build-katte-extreme/bin/test-json-schema")
set_tests_properties([=[test-json-schema]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;261;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-chat-auto-parser]=] "/workspace/build-katte-extreme/bin/test-chat-auto-parser")
set_tests_properties([=[test-chat-auto-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/workspace" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;262;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-chat-template]=] "/workspace/build-katte-extreme/bin/test-chat-template")
set_tests_properties([=[test-chat-template]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;263;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-log]=] "/workspace/build-katte-extreme/bin/test-log")
set_tests_properties([=[test-log]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;266;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-peg-parser]=] "/workspace/build-katte-extreme/bin/test-peg-parser")
set_tests_properties([=[test-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;267;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-download-model]=] "/usr/bin/cmake" "-DDEST=/workspace/build-katte-extreme/tinyllamas/stories15M-q4_0.gguf" "-DNAME=tinyllamas/stories15M-q4_0.gguf" "-DHASH=SHA256=66967fbece6dbe97886593fdbb73589584927e29119ec31f08090732d1861739" "-P" "/workspace/cmake/download-models.cmake")
set_tests_properties([=[test-download-model]=] PROPERTIES  FIXTURES_SETUP "test-download-model" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;288;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-thread-safety]=] "/workspace/build-katte-extreme/bin/test-thread-safety" "-m" "/workspace/build-katte-extreme/tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties([=[test-thread-safety]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;296;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-arg-parser]=] "/workspace/build-katte-extreme/bin/test-arg-parser")
set_tests_properties([=[test-arg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;299;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-model-resolution]=] "/workspace/build-katte-extreme/bin/test-model-resolution")
set_tests_properties([=[test-model-resolution]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;300;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-opt]=] "/workspace/build-katte-extreme/bin/test-opt")
set_tests_properties([=[test-opt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;306;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-model-load-cancel]=] "/workspace/build-katte-extreme/bin/test-model-load-cancel")
set_tests_properties([=[test-model-load-cancel]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;312;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-autorelease]=] "/workspace/build-katte-extreme/bin/test-autorelease")
set_tests_properties([=[test-autorelease]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;313;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-backend-sampler]=] "/workspace/build-katte-extreme/bin/test-backend-sampler")
set_tests_properties([=[test-backend-sampler]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;314;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-state-restore-fragmented]=] "/workspace/build-katte-extreme/bin/test-state-restore-fragmented" "-m" "/workspace/build-katte-extreme/tinyllamas/stories15M-q4_0.gguf")
set_tests_properties([=[test-state-restore-fragmented]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;318;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-barrier]=] "/workspace/build-katte-extreme/bin/test-barrier")
set_tests_properties([=[test-barrier]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;327;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-fns]=] "/workspace/build-katte-extreme/bin/test-quantize-fns")
set_tests_properties([=[test-quantize-fns]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;328;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-perf]=] "/workspace/build-katte-extreme/bin/test-quantize-perf")
set_tests_properties([=[test-quantize-perf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;329;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-rope]=] "/workspace/build-katte-extreme/bin/test-rope")
set_tests_properties([=[test-rope]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;330;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-col2im-1d]=] "/workspace/build-katte-extreme/bin/test-col2im-1d")
set_tests_properties([=[test-col2im-1d]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;331;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-mtmd-c-api]=] "/workspace/build-katte-extreme/bin/test-mtmd-c-api")
set_tests_properties([=[test-mtmd-c-api]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;336;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-mtmd-impl]=] "/workspace/build-katte-extreme/bin/test-mtmd-impl")
set_tests_properties([=[test-mtmd-impl]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;340;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-gguf-model-data]=] "/workspace/build-katte-extreme/bin/test-gguf-model-data")
set_tests_properties([=[test-gguf-model-data]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;40;add_test;/workspace/tests/CMakeLists.txt;354;llama_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-quant-type-selection]=] "/workspace/build-katte-extreme/bin/test-quant-type-selection")
set_tests_properties([=[test-quant-type-selection]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;357;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-gguf]=] "/workspace/build-katte-extreme/bin/test-gguf")
set_tests_properties([=[test-gguf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;371;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
add_test([=[test-alloc]=] "/workspace/build-katte-extreme/bin/test-alloc")
set_tests_properties([=[test-alloc]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;110;add_test;/workspace/tests/CMakeLists.txt;374;llama_build_and_test;/workspace/tests/CMakeLists.txt;0;")
